import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useState, PropsWithChildren } from 'react';
import { MdMenu, MdClose } from 'react-icons/md';

export const Layout = ({ children }: PropsWithChildren<unknown>): JSX.Element => {
  const router = useRouter();
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [isShowNavbar, setIsShowNavbar] = useState(false);
  const [path, setPath] = useState('home')

  function onChangeMenu(route: any) {
      router.push(route)
      setPath(route.substring(1))
      setIsShowNavbar(false)
  }

  return (
    <>
      <Head>
        <title>Staycation.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id='container' className='container-body'>
      <header className={`shadow p-5 bg-white z-50`}>
        <div>
          <h1>Stay<span className='text-darkblue'>cation.</span></h1>
          <div className={'hidden md:flex flex-row gap-10'}>
            <a className={`${path === 'home' && 'text-lightblue'} hover:cursor-pointer hover:text-darkgreen duration-300`} onClick={() => onChangeMenu('/home')}>Home</a>
            <a className={`${path === 'about' && 'text-lightblue'} hover:cursor-pointer hover:text-darkgreen duration-300`} onClick={() => onChangeMenu('/browse')}>Browse by</a>
            <a className={`${path === 'portfolio' && 'text-lightblue'} hover:cursor-pointer hover:text-darkgreen duration-300`} onClick={() => onChangeMenu('/stories')}>Stories</a>
            <a className={`${path === 'certificate' && 'text-lightblue'} hover:cursor-pointer hover:text-darkgreen duration-300`} onClick={() => onChangeMenu('/agents')}>Agents</a>
          </div>

          <button onClick={() => setIsShowNavbar(!isShowNavbar)} className={'flex flex-row md:hidden'}>
            {isShowNavbar ? <MdClose className='text-4xl' /> : <MdMenu className='text-4xl' />}
          </button>
        </div>
      </header>

      <div className={`z-50 fixed flex flex-col ${isShowNavbar ? 'visible' : 'invisible'} md:hidden gap-10 ${isDarkMode ? 'bg-gray-700' : 'bg-white'} min-h-40 w-full mt-20 rounded-b-[20px] p-10 shadow-2xl`}>
        <a onClick={() => onChangeMenu('/home')}>Home</a>
        <a onClick={() => onChangeMenu('/about')}>Browse By</a>
        <a onClick={() => onChangeMenu('/portfolio')}>Stories</a>
        <a onClick={() => onChangeMenu('/certificate')}>Agents</a>
      </div>

      <main>{children}</main>
    </div>
    </>
  )
}
